Login tests migration branch (#6769)
Re-enables e2e test jobs. 
Bumps protractor version.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -13,11 +13,11 @@ services:
   - docker
 
 env:
-#  matrix:
-#    - TEST_SUITE=integration NODE_VERSION=8
-#    - TEST_SUITE=integration NODE_VERSION=10
-#    - TEST_SUITE=integration NODE_VERSION=12
-#    - TEST_SUITE=performance NODE_VERSION=12
+  matrix:
+    - TEST_SUITE=integration NODE_VERSION=8
+    - TEST_SUITE=integration NODE_VERSION=10
+    - TEST_SUITE=integration NODE_VERSION=12
+    # - TEST_SUITE=performance NODE_VERSION=12
   global:
     - COUCH_URL=http://admin:pass@localhost:5984/medic-test
     - COUCH_NODE_NAME=nonode@nohost
@@ -56,20 +56,20 @@ before_script:
   - echo "COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER"
   - COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER horti --local --install=medic:medic:test-$TRAVIS_BUILD_NUMBER > tests/logs/horti.log &
 
-#script:
-#  - |
-#    if [[ "$TEST_SUITE" = 'integration' ]]; then
-#      node --stack_size=10000 `which grunt` ci-e2e
-#    elif [[ "$TEST_SUITE" = 'performance' ]]; then
-#      node --stack_size=10000 `which grunt` ci-performance
-#    else
-#      echo "ERROR No or unknown value for TEST_SUITE env var ('${TEST_SUITE}')."
-#      exit 1
-#    fi
+script:
+  - |
+    if [[ "$TEST_SUITE" = 'integration' ]]; then
+      node --stack_size=10000 `which grunt` ci-e2e
+    elif [[ "$TEST_SUITE" = 'performance' ]]; then
+      node --stack_size=10000 `which grunt` ci-performance
+    else
+      echo "ERROR No or unknown value for TEST_SUITE env var ('${TEST_SUITE}')."
+      exit 1
+    fi
 
 stages:
   - compile
-  #- test
+  - test
   #- publish
 
 jobs:
