Just run the "compile" stage, pls.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -56,21 +56,21 @@ before_script:
   - echo "COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER"
   - COUCH_URL=$COUCH_URL HORTI_BUILDS_SERVER=$UPLOAD_URL/$BUILDS_SERVER horti --local --install=medic:medic:test-$TRAVIS_BUILD_NUMBER > tests/logs/horti.log &
 
-script:
-  - |
-    if [[ "$TEST_SUITE" = 'integration' ]]; then
-      node --stack_size=10000 `which grunt` ci-e2e
-    elif [[ "$TEST_SUITE" = 'performance' ]]; then
-      node --stack_size=10000 `which grunt` ci-performance
-    else
-      echo "ERROR No or unknown value for TEST_SUITE env var ('${TEST_SUITE}')."
-      exit 1
-    fi
+#script:
+#  - |
+#    if [[ "$TEST_SUITE" = 'integration' ]]; then
+#      node --stack_size=10000 `which grunt` ci-e2e
+#    elif [[ "$TEST_SUITE" = 'performance' ]]; then
+#      node --stack_size=10000 `which grunt` ci-performance
+#    else
+#      echo "ERROR No or unknown value for TEST_SUITE env var ('${TEST_SUITE}')."
+#      exit 1
+#    fi
 
 stages:
   - compile
   #- test
-  - publish
+  #- publish
 
 jobs:
   include:
@@ -83,19 +83,23 @@ jobs:
       script:
         - node --stack_size=10000 `which grunt` ci-compile
       after_script:
-        - node --stack_size=10000 `which grunt` publish-for-testing
-    - stage: publish
-      if: type != pull_request
-      env: NODE_VERSION=12
-      before_script: # overwrite default
-      script:
+        #- node --stack_size=10000 `which grunt` publish-for-testing
         - cd scripts/travis
         - npm install
         - node ./publish.js
         - cd ../../
-      after_failure: # overwrite default
-      after_script:
-        - node scripts/travis/cleanup.js # clean up testing ddoc
+#    - stage: publish
+#      if: type != pull_request
+#      env: NODE_VERSION=12
+#      before_script: # overwrite default
+#      script:
+#        - cd scripts/travis
+#        - npm install
+#        - node ./publish.js
+#        - cd ../../
+#      after_failure: # overwrite default
+#      after_script:
+#        - node scripts/travis/cleanup.js # clean up testing ddoc
 
 after_failure:
   - node scripts/travis/cleanup.js # clean up testing ddoc
