not obvious...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -70,11 +70,13 @@ jobs:
         - ./scripts/travis/couch-config
         - mkdir tests/logs
       script:
+        # TODO combine these first four into one grunt task so it fails properly
         - node --stack_size=10000 `which grunt` ci-build       # build the app
         - node --stack_size=10000 `which grunt` ci-unit        # run static analysis and unit tests
         - node --stack_size=10000 `which grunt` ci-integration # run integration tests
         - cd config/standard && npm ci && npm run travis       # run standard config tests
         - node --stack_size=10000 `which grunt` publish-for-testing
+      after_failure: # overwrite default
     - stage: publish
       if: type != pull_request
       env: NODE_VERSION=10
@@ -83,32 +85,33 @@ jobs:
         - cd scripts/travis
         - npm install
         - node ./publish.js
+      after_failure: # overwrite default
 
-# after_failure:
-#   - pip install --user awscli
-#   - |
-#     (cd tests/logs
-#       for log in $(ls *.log); do
-#         echo "---------- $log ----------"
-#         tail "$log"
-#         echo "--------------------------"
-#       done
-#     )
+after_failure:
+  - pip install --user awscli
+  - |
+    (cd tests/logs
+      for log in $(ls *.log); do
+        echo "---------- $log ----------"
+        tail "$log"
+        echo "--------------------------"
+      done
+    )
 
-#     [[ "$TRAVIS_BUILD_STAGE_NAME" = "Test" ]] || return
+    [[ "$TRAVIS_BUILD_STAGE_NAME" = "Test" ]] || return
 
-#     if [[ "$TRAVIS_PULL_REQUEST" = true ]]; then
-#       S3_PATH=s3://medic-e2e/PR_$TRAVIS_PULL_REQUEST
-#     else
-#       S3_PATH=s3://medic-e2e/BUILD_$TRAVIS_BUILD_NUMBER/JOB_$TRAVIS_JOB_NUMBER
-#     fi
+    if [[ "$TRAVIS_PULL_REQUEST" = true ]]; then
+      S3_PATH=s3://medic-e2e/PR_$TRAVIS_PULL_REQUEST
+    else
+      S3_PATH=s3://medic-e2e/BUILD_$TRAVIS_BUILD_NUMBER/JOB_$TRAVIS_JOB_NUMBER
+    fi
 
-#     echo "Uploading logs and screenshots to ${S3_PATH}..."
+    echo "Uploading logs and screenshots to ${S3_PATH}..."
 
-#     docker logs couch > tests/logs/couch.log 2>&1
+    docker logs couch > tests/logs/couch.log 2>&1
 
-#     aws s3 cp tests/results "$S3_PATH"/test-results --recursive
-#     aws s3 cp tests/logs "$S3_PATH"/ --recursive
+    aws s3 cp tests/results "$S3_PATH"/test-results --recursive
+    aws s3 cp tests/logs "$S3_PATH"/ --recursive
 
 #notifications:
 #  slack:
